---
- name: Ensure InfluxDB dirs exists.
  file:
    path: "{{ item }}"
    state: directory
    owner: influxdb
    group: influxdb
  with_items:
    - "{{ influxdb_config_meta_dir }}"
    - "{{ influxdb_config_data_dir }}"
    - "{{ influxdb_config_wal_dir }}"
    - "{{ influxdb_config_hh_dir }}"
  when: influxdb_config_use_template

- name: Copy InfluxDB config.
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
  notify: restart influxdb
  when: influxdb_config_use_template
