---
- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- include: configure-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Start and enable InfluxDB.
  service: name=influxdb state=started enabled=yes
