---
- name: download influxdb package
  get_url:
    url: https://s3.amazonaws.com/influxdb/influxdb_{{ influxdb_version }}-1_amd64.deb
    dest: /tmp/influxdb_{{ influxdb_version }}-1_amd64.deb

- name: install influxdb
  # FIXME: https://github.com/ansible/ansible-modules-core/issues/2430
  # Bug in "apt" module causes task to always report {"changed": true}
  apt: deb=/tmp/influxdb_{{ influxdb_version }}-1_amd64.deb state=present

