---
- name: download influxdb package
  get_url:
    url: https://s3.amazonaws.com/influxdb/influxdb-{{ influxdb_version }}-1.x86_64.rpm
    dest: /tmp/influxdb-{{ influxdb_version }}-1.x86_64.rpm

- name: install influxdb
  package: name=/tmp/influxdb-{{ influxdb_version }}-1.x86_64.rpm state=present
