---
- name: Download InfluxDB package.
  get_url:
    url: http://s3.amazonaws.com/influxdb/influxdb-{{ influxdb_version }}-1.x86_64.rpm
    dest: /tmp/influxdb-{{ influxdb_version }}-1.x86_64.rpm

- name: Install InfluxDB.
  yum: name=/tmp/influxdb-{{ influxdb_version }}-1.x86_64.rpm state=present
